name: Update Firestore with FRED Data

on:
  schedule:
    - cron: '0 16 * * *'  # 每天 GMT+8 的 00:00 執行（16:00 UTC）
  workflow_dispatch:

jobs:
  update-firestore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios firebase-admin

      - name: Fetch FRED Data and Upload to Firestore
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.AIzaSyCveAp3D6ySKTuC_Vfu8IZGhvkx1GKEkOE }}
          FRED_API_KEY: ${{ secrets.a5ed1058170be50b5092b6cd0f669117 }}
        run: node scripts/updateFirestore.js
